/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEnd;

import com.selfCarWash.Machine;
import com.selfCarWash.WashPrograms;
import com.selfCarWash.programs.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;

/**
 * @author Administrator123
 */
public class MachineDisplay extends javax.swing.JFrame {

    /**
     * Creates new form MachineDisplay
     */
    public MachineDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preWashButton = new javax.swing.JButton();
        soapButton = new javax.swing.JButton();
        rinsButton = new javax.swing.JButton();
        waxButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        remainingTimeLabel = new javax.swing.JLabel();
        currentProgramLabel = new javax.swing.JLabel();
        washProgramsTextField = new javax.swing.JTextField();
        timeLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        insertedMoneyCheck = new javax.swing.JCheckBox();
        inserCreditLabel = new javax.swing.JLabel();
        DisplayPricesButton = new javax.swing.JButton();
        showPriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        preWashButton.setText("PreWash");
        preWashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preWashButtonActionPerformed(evt);
            }
        });

        soapButton.setText("Soap");
        soapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soapButtonActionPerformed(evt);
            }
        });

        rinsButton.setText("Rins");
        rinsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rinsButtonActionPerformed(evt);
            }
        });

        waxButton.setText("Wax");
        waxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waxButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.red);

        remainingTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        remainingTimeLabel.setText("Remaining time");

        currentProgramLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        currentProgramLabel.setText("Current program:");

        washProgramsTextField.setText("Pause");

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeLabel.setText("03:00");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        insertedMoneyCheck.setText("Inserted money");
        insertedMoneyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertedMoneyCheckActionPerformed(evt);
            }
        });

        inserCreditLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inserCreditLabel.setText("Please insert credit before pressing Start button");

        DisplayPricesButton.setText("Display prices");
        DisplayPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayPricesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(currentProgramLabel)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(remainingTimeLabel)
                        .addGap(110, 110, 110)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(washProgramsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(showPriceLabel)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DisplayPricesButton)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(startButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inserCreditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertedMoneyCheck)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remainingTimeLabel)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DisplayPricesButton)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentProgramLabel)
                            .addComponent(washProgramsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPriceLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inserCreditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(insertedMoneyCheck)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(19, 19, 19))
        );

        inserCreditLabel.getAccessibleContext().setAccessibleName("jLabel4");
        showPriceLabel.getAccessibleContext().setAccessibleName("displayLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(preWashButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rinsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waxButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preWashButton)
                        .addGap(27, 27, 27)
                        .addComponent(soapButton)
                        .addGap(33, 33, 33)
                        .addComponent(rinsButton)
                        .addGap(27, 27, 27)
                        .addComponent(waxButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Machine machine = Machine.getInstance();
    WashPrograms washPrograms;
    Timer timer;
    int second, minute;
    String ddSecond, ddMinute;
    DecimalFormat dFormat = new DecimalFormat("00");
    boolean activeButtons = false;
    boolean canStart = false;

    public void countdownTimer() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                second--;
                ddSecond = dFormat.format(second);
                ddMinute = dFormat.format(minute);
                timeLabel.setText(ddMinute + ":" + ddSecond);

                if (second == -1) {
                    second = 59;
                    minute--;
                    ddSecond = dFormat.format(second);
                    ddMinute = dFormat.format(minute);
                    timeLabel.setText(ddMinute + ":" + ddSecond);
                }
                if (minute == 0 && second == 0) {
                    activeButtons = false;
                    washPrograms = new Pause();
                    washProgramsTextField.setText("Pause");
                    insertedMoneyCheck.setSelected(false);
                    showPriceLabel.setText("");

                    timer.stop();
                }
            }
        });
    }

    public void initializeTimer() {
        countdownTimer();
        second = 0;
        minute = 3;
        timeLabel.setText("03:00");
        timer.start();
    }

    private void preWashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preWashButtonActionPerformed
        // TODO add your handling code here:
        if (activeButtons) {
            washPrograms = new PreWash();
            machine.washingProgramsMenu(washPrograms);
            washProgramsTextField.setText("PreWash");
        }
    }//GEN-LAST:event_preWashButtonActionPerformed

    private void soapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soapButtonActionPerformed
        // TODO add your handling code here:
        if (activeButtons) {

            washPrograms = new Soap();
            machine.washingProgramsMenu(washPrograms);
            washProgramsTextField.setText("Soap");
        }
    }//GEN-LAST:event_soapButtonActionPerformed

    private void rinsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rinsButtonActionPerformed
        // TODO add your handling code here:
        if (activeButtons) {
            washPrograms = new Rins();
            machine.washingProgramsMenu(washPrograms);
            washProgramsTextField.setText("Rins");
        }
    }//GEN-LAST:event_rinsButtonActionPerformed

    private void waxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waxButtonActionPerformed
        if (activeButtons) {
            washPrograms = new Wax();
            machine.washingProgramsMenu(washPrograms);
            washProgramsTextField.setText("Wax");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_waxButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (canStart) {
            activeButtons = true;
            initializeTimer();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    private void DisplayPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayPricesButtonActionPerformed
        showPriceLabel.setText("3 ron - 5 minutes");
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayPricesButtonActionPerformed

    private void insertedMoneyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertedMoneyCheckActionPerformed
        if (insertedMoneyCheck.isSelected()) {
            canStart = true;
            machine.counterWashes++;
        } else canStart = false;        // TODO add your handling code here:
    }//GEN-LAST:event_insertedMoneyCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MachineDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MachineDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MachineDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MachineDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MachineDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisplayPricesButton;
    private javax.swing.JLabel currentProgramLabel;
    private javax.swing.JLabel inserCreditLabel;
    private javax.swing.JCheckBox insertedMoneyCheck;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton preWashButton;
    private javax.swing.JLabel remainingTimeLabel;
    private javax.swing.JButton rinsButton;
    private javax.swing.JLabel showPriceLabel;
    private javax.swing.JButton soapButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField washProgramsTextField;
    private javax.swing.JButton waxButton;
    // End of variables declaration//GEN-END:variables

}
